# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: false
sudo: required
apt_packages:
  - r-cran-rjava
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpoppler-cpp-dev
  - sudo $(which R) CMD javareconf
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
